addons:
  apt:
    packages:
    - python-scipy
language: python
python:
  - "2.7"
  - "3.5"
install: 
  - "if [[ \"$TRAVIS_PYTHON_VERSION\" == \"2.7\" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;fi"
  - "bash miniconda.sh -b -p $HOME/miniconda"
  - "export PATH=\"$HOME/miniconda/bin:$PATH\""
  - "hash -r"
  - "conda config --set always_yes yes --set changeps1 no"
  - "conda update -q conda"
  - "conda info -a"
  - "conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION praw scikit-learn sqlalchemy"
  - "source activate test-environment"
  - "python setup.py install"
script: python test.py
